# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Pizza' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pizza
  pod ‘MapboxNavigation’, ‘~> 0.37.0’

  target 'PizzaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
